---
- name: Update Apt
  ansible.builtin.apt:
    update_cache: true

- name: Install APT packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - cmake
      - curl
      - dmenu
      - dunst
      - feh
      - git
      - htop
      - jq
      - keychain
      - libbz2-dev
      - libffi-dev
      - libfuse-dev
      - liblzma-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libyaml-dev
      - mplayer
      - rofi
      - shellcheck
      - tmux
      - tree
      - xclip
      - xmobar
      - xmonad
      - xscreensaver
      - zlib1g-dev
      - zsh
