---
- name: Download chezmoi installer
  ansible.builtin.get_url:
    url: "https://get.chezmoi.io/lb"
    dest: "/tmp/install-chezmoi"
    mode: '0755'

- name: Install chezmoi
  ansible.builtin.command:
    cmd: "/tmp/install-chezmoi -b {{ paths.local_bin }}"
    creates: "{{ chezmoi.executable_path }}"

- name: Apply dotfiles
  ansible.builtin.command:
    cmd: >
      "{{ chezmoi.executable_path }}" init
      --apply {{ dotfiles.repo.https_url }}
      --promptString "Email address={{ email }}"
    creates: "{{ chezmoi.source_path }}"

- name: Change dotfiles origin url # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: git remote set-url origin {{ dotfiles.repo.ssh_url }}
    chdir: "{{ paths.local_share }}/chezmoi"
  changed_when: true
