---
- name: Create directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - code
    - packages
    - sources
    - screenshots
    - screensavers

- name: Run dotfiles tasks
  ansible.builtin.import_tasks: dotfiles.yml

- name: Run asdf tasks
  ansible.builtin.import_tasks: asdf.yml

- name: Run ohmyzsh tasks
  ansible.builtin.import_tasks: ohmyzsh.yml

- name: Run nvim tasks
  ansible.builtin.import_tasks: nvim.yml

- name: Run fzf tasks
  ansible.builtin.import_tasks: fzf.yml

- name: Run golang tasks
  ansible.builtin.import_tasks: golang.yml

- name: Run python tasks
  ansible.builtin.import_tasks: python.yml

- name: Run rust tasks
  ansible.builtin.import_tasks: rust.yml
