name: Build and Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches:
      - master

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: "docker build . -f dockerfiles/Dockerfile.${{ matrix.os }}"
