name: Build and Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches:
      - master

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build docker image
        run: >
          docker build .
          -f dockerfiles/Dockerfile.${{ matrix.os }}
          -t jackhxs/pangu

      - name: Lint
        run: >
          docker run jackhxs/pangu ansible-lint

      - name: Build and test
        run: >
          docker run jackhxs/pangu
          ansible-playbook --verbose playbooks/dev_box.yml
